USE [REZAKWB01]
GO

/****** Object:  StoredProcedure [dbo].[AAII_SALESCHANNEL_DAILY]    Script Date: 10/26/2015 10:37:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









--ALTER PROCEDURE [dbo].[AAII_SALESCHANNEL_DAILY]

--AS



BEGIN


DECLARE     @MYDateUTC			 datetime,
			@dateStart      datetime,
			@dateEnd		 datetime,
			@test				 datetime
 

	--select @MYDateUTC  = GETDATE()
	
	--SET @dateEnd   = DATEADD(MM,DATEDIFF(MM,0,DATEADD(MM,0,@MYDateUTC)),0)
 --   SET @dateStart = DATEADD(MONTH,-1,@dateEnd)
	

	--print @MYDateUTC 
	--print @dateStart
	--print @dateEnd
			
select @MYDateUTC  = DATEADD(HH,+8,GetDate())


SET @dateStart= CAST(CONVERT(VARCHAR, DateAdd(day,-1,@MYDateUTC), 101) AS DateTime)
SET @dateEnd= CAST(CONVERT(VARCHAR, @MYDateUTC, 101) AS DateTime)

if DATEPART(DAY,@MYDateUTC) = 5
Begin

	
	SET @dateStart= DATEADD(MM,DATEDIFF(MM,0,DATEADD(MM,0,@MYDateUTC)),0)
	SET @dateStart= DATEADD(MONTH,-1,@dateStart)
	
end

print @MYDateUTC
print @dateStart
print @dateEnd



BEGIN TRY DROP TABLE #PASSENGERS END TRY BEGIN CATCH END CATCH



SELECT convert(date,BK.BOOKINGDATE) BOOKINGDATE,BK.BOOKINGID,BK.CREATEDAGENTID,

BP.PASSENGERID,

PJS.SEGMENTID,PJS.DEPARTUREDATE,PJS.DEPARTURESTATION,PJS.ARRIVALSTATION,PJS.JOURNEYNUMBER,PJS.SEGMENTNUMBER,--PJS.FARECLASSOFSERVICE,

PJS.INTERNATIONAL,

AR.ROLECODE,

IL.CARRIERCODE,

AG.ORGANIZATIONCODE,AG.LOCATIONCODE,

DS.COUNTRYCODE DEPARTURECOUNTRYCODE,

ARS.COUNTRYCODE ARRIVALCOUNTRYCODE,

DC.NAME DEPARTURECOUNTRY,

AC.NAME ARRIVALCOUNTRY,

PJC.CURRENCYCODE,

(CASE WHEN IL.CARRIERCODE IN ('AK','D7') THEN 'MYR'

	  WHEN IL.CARRIERCODE IN ('FD','XJ') THEN 'THB'

	  WHEN IL.CARRIERCODE = 'QZ' THEN 'IDR'

	  WHEN IL.CARRIERCODE = 'XT' THEN 'USD'

	  WHEN IL.CARRIERCODE IN ('PQ','Z2') THEN 'PHP'

	  WHEN IL.CARRIERCODE = 'I5' THEN 'INR'

	  ELSE 'MYR' END) AOCCURRENCY,

SUM(CASE WHEN CHARGETYPE IN (0,1,7,19) THEN PJC.CHARGEAMOUNT*CTM.POSITIVENEGATIVEFLAG ELSE 0 END)
+ SUM(CASE WHEN PJC.CHARGECODE IN ('KLIA2')
THEN PJC.CHARGEAMOUNT*CTM.POSITIVENEGATIVEFLAG ELSE 0 END) FARE_REVENUE,

SUM(CASE WHEN CHARGECODE IN ('FUEL','FUEX','DOMS') THEN PJC.CHARGEAMOUNT*CTM.POSITIVENEGATIVEFLAG ELSE 0 END) FUEL_REV 

INTO #PASSENGERS

FROM

(SELECT * FROM ODS.BOOKING

WHERE BOOKINGDATE >= @dateStart AND BOOKINGDATE < @dateEnd AND STATUS IN (2,3)) BK
--WHERE BOOKINGDATE >= '2015-10-15' AND BOOKINGDATE < '2015-10-18' AND STATUS IN (2,3)) BK

JOIN

ODS.BOOKINGPASSENGER BP

ON

BK.BOOKINGID = BP.BOOKINGID

JOIN

ODS.PASSENGERJOURNEYSEGMENT PJS

ON

BP.PASSENGERID = PJS.PASSENGERID

JOIN

ODS.AGENTROLE AR

ON

BK.CREATEDAGENTID = AR.AGENTID

JOIN

ODS.PASSENGERJOURNEYLEG PJL

ON

PJS.PASSENGERID = PJL.PASSENGERID

AND

PJS.SEGMENTID = PJL.SEGMENTID

JOIN

ODS.INVENTORYLEG IL

ON

PJL.INVENTORYLEGID = IL.INVENTORYLEGID

AND IL.STATUS <> 2
AND IL.LID > 0

JOIN

ODS.AGENT AG

ON

BK.CREATEDAGENTID = AG.AGENTID

JOIN

ODS.PASSENGERJOURNEYCHARGE PJC

ON

PJL.PASSENGERID = PJC.PASSENGERID

AND

PJL.SEGMENTID = PJC.SEGMENTID

JOIN

DW.CHARGETYPEMATRIX CTM

ON

PJC.CHARGETYPE = CTM.CHARGETYPEID

JOIN

ODS.STATION DS

ON

PJS.DEPARTURESTATION = DS.StationCode

JOIN

ODS.Station ARS 

ON

PJS.ARRIVALSTATION = ARS.STATIONCODE

JOIN

ODS.COUNTRY DC

ON

DS.COUNTRYCODE = DC.COUNTRYCODE

JOIN

ODS.COUNTRY AC

ON

ARS.COUNTRYCODE = AC.COUNTRYCODE

GROUP BY BK.BOOKINGDATE,BK.BOOKINGID,BK.CREATEDAGENTID,

BP.PASSENGERID,

PJS.SEGMENTID,PJS.DEPARTUREDATE,PJS.DEPARTURESTATION,PJS.ARRIVALSTATION,PJS.JOURNEYNUMBER,PJS.SEGMENTNUMBER,--PJS.FARECLASSOFSERVICE,

PJS.INTERNATIONAL,

AR.ROLECODE,

IL.CARRIERCODE,

AG.ORGANIZATIONCODE,AG.LOCATIONCODE,

DS.COUNTRYCODE,

ARS.COUNTRYCODE,

DC.NAME,

AC.NAME,

PJC.CURRENCYCODE,

(CASE WHEN IL.CARRIERCODE IN ('AK','D7') THEN 'MYR'

	  WHEN IL.CARRIERCODE IN ('FD','XJ') THEN 'THB'

	  WHEN IL.CARRIERCODE = 'QZ' THEN 'IDR'

	  WHEN IL.CARRIERCODE = 'XT' THEN 'USD'

	  WHEN IL.CARRIERCODE IN ('PQ','Z2') THEN 'PHP'

	  WHEN IL.CARRIERCODE = 'I5' THEN 'INR'

	  ELSE 'MYR' END)



BEGIN TRY DROP TABLE #PASSENGERPOS END TRY BEGIN CATCH END CATCH



SELECT BK.BOOKINGID,

PJS.PASSENGERID,PJS.DEPARTURESTATION,

ST.COUNTRYCODE POSCOUNTRYCODE,

CTY.NAME POSCOUNTRYNAME,CTY.DEFAULTCURRENCYCODE POSCOUNTRYCURRENCY

INTO #PASSENGERPOS

FROM

(SELECT * FROM ODS.BOOKING where bookingid in (select distinct bookingid from #PASSENGERS)) BK

--WHERE BOOKINGDATE >= @dateStart AND BOOKINGDATE < @dateEnd AND STATUS IN (2,3)) BK

JOIN

ODS.BOOKINGPASSENGER BP

ON

BK.BOOKINGID = BP.BOOKINGID

JOIN

ODS.PASSENGERJOURNEYSEGMENT PJS

ON

BP.PASSENGERID = PJS.PASSENGERID

AND

PJS.JOURNEYNUMBER = 1 AND PJS.SEGMENTNUMBER = 1

JOIN

ODS.STATION ST

ON

PJS.DEPARTURESTATION = ST.STATIONCODE

JOIN

ODS.COUNTRY CTY

ON

ST.COUNTRYCODE = CTY.COUNTRYCODE







BEGIN TRY DROP TABLE #PASSENGERALL END TRY BEGIN CATCH END CATCH





SELECT P.*,PP.POSCOUNTRYCODE,PP.POSCOUNTRYNAME,PP.POSCOUNTRYCURRENCY

INTO #PASSENGERALL

FROM

#PASSENGERS P

LEFT JOIN

#PASSENGERPOS PP

ON

P.BOOKINGID = PP.BOOKINGID

AND

P.PASSENGERID = PP.PASSENGERID





BEGIN TRY DROP TABLE #PASSENGERCHANNEL END TRY BEGIN CATCH END CATCH



SELECT distinct P.*,

case when SC.SalesChannelRpt = 'Corporate' and (P.OrganizationCode like '%A%' OR P.OrganizationCode like '%B%' OR P.OrganizationCode like '%C%' OR

		 P.OrganizationCode like '%D%' OR P.OrganizationCode like '%E%' OR P.OrganizationCode like '%F%' OR P.OrganizationCode like '%G%' OR

		 P.OrganizationCode like '%H%' OR P.OrganizationCode like '%I%' OR P.OrganizationCode like '%J%' OR P.OrganizationCode like '%K%' OR

		 P.OrganizationCode like '%L%' OR P.OrganizationCode like '%M%' OR P.OrganizationCode like '%N%' OR P.OrganizationCode like '%O%' OR

		 P.OrganizationCode like '%P%' OR P.OrganizationCode like '%Q%' OR P.OrganizationCode like '%R%' OR P.OrganizationCode like '%S%' OR

		 P.OrganizationCode like '%T%' OR P.OrganizationCode like '%U%' OR P.OrganizationCode like '%V%' OR P.OrganizationCode like '%W%' OR

		 P.OrganizationCode like '%X%' OR P.OrganizationCode like '%Y%' OR P.OrganizationCode like '%Z%') then 'Corporate - Direct'

	 when SC.SalesChannelRpt = 'Corporate' and (P.OrganizationCode not like '%A%' AND P.OrganizationCode not like '%B%' AND P.OrganizationCode not like '%C%' AND

		 P.OrganizationCode not like '%D%' AND P.OrganizationCode not like '%E%' AND P.OrganizationCode not like '%F%' AND P.OrganizationCode not like '%G%' AND

		 P.OrganizationCode not like '%H%' AND P.OrganizationCode not like '%I%' AND P.OrganizationCode not like '%J%' AND P.OrganizationCode not like '%K%' AND

		 P.OrganizationCode not like '%L%' AND P.OrganizationCode not like '%M%' AND P.OrganizationCode not like '%N%' AND P.OrganizationCode not like '%O%' AND

		 P.OrganizationCode not like '%P%' AND P.OrganizationCode not like '%Q%' AND P.OrganizationCode not like '%R%' AND P.OrganizationCode not like '%S%' AND

		 P.OrganizationCode not like '%T%' AND P.OrganizationCode not like '%U%' AND P.OrganizationCode not like '%V%' AND P.OrganizationCode not like '%W%' AND

		 P.OrganizationCode not like '%X%' AND P.OrganizationCode not like '%Y%' AND P.OrganizationCode not like '%Z%') then 'Corporate - TMC'

	 when SalesChannelRpt = 'Corporate' and P.OrganizationCode IS NULL then SalesChannelRpt

	 when SalesChannelRpt = 'Call Centre' and LocationCode in ('KUL','ORY','AUH','ICN','HND','MNL') then 'Call Centre - Scicom'

	 when SalesChannelRpt = 'Call Centre' and LocationCode in ('MAA','DEL') then 'Call Centre - Sutherland'

	 when SalesChannelRpt = 'Call Centre' and LocationCode in ('SZX','CAN') then 'Call Centre - Sonic'

	 when SalesChannelRpt = 'Call Centre' and LocationCode in ('CGK') then 'Call Centre - IAA'

	 when SalesChannelRpt = 'Call Centre' and LocationCode in ('DMK','BKK') then 'Call Centre - TAA'

	 else SalesChannelRpt

end SALESCHANNEL,

SCG.GROUPING,SCG.CATEGORY,SA.ORGANIZATIONNAME,SA.COUNTRYCODE ORGANIZATIONCOUNTRYCODE

INTO #PASSENGERCHANNEL

FROM

(SELECT  * FROM #PASSENGERALL) P

LEFT JOIN

SAT_JK_SALESCHANNEL SC

ON

P.ROLECODE = SC.ROLECODE

LEFT JOIN

SAT_JK_SALESCHANNEL_GRP SCG

ON

SC.SALESCHANNELRPT = SCG.CHANNELBREAKDOWN

AND

SCG.CHANNELBREAKDOWN+SCG.CATEGORY <> 'OthersThird Party'

LEFT JOIN

ODS.ORGANIZATION SA

ON

P.ORGANIZATIONCODE = SA.ORGANIZATIONCODE




/*

SELECT TOP 100 * FROM ODS.ORGANIZATION

SELECT TOP 100 * FROM REF_SALES_AGENCY_LIST

*/




BEGIN TRY DROP TABLE #PASSENGERALLCURRENCY1 END TRY BEGIN CATCH END CATCH





SELECT P.*,

(CASE WHEN P.CURRENCYCODE <> 'MYR' THEN P.FARE_REVENUE*(1/CC.CONVERSIONRATE) ELSE P.FARE_REVENUE END) FARE_REV_MYR,

(CASE WHEN P.CURRENCYCODE <> 'MYR' THEN P.FUEL_REV*(1/CC.CONVERSIONRATE) ELSE P.FUEL_REV END) FUEL_REV_MYR

INTO #PASSENGERALLCURRENCY1

FROM

#PASSENGERCHANNEL P

LEFT JOIN

DW.CURRENCYCONVERSIONHISTORYDECOMPRESSED CC

ON

CONVERT(DATE,CC.CONVERSIONDATE,110) = CONVERT(DATE,P.BOOKINGDATE,110)

AND

CC.FROMCURRENCYCODE = 'MYR'

AND

CC.TOCURRENCYCODE = P.CURRENCYCODE




BEGIN TRY DROP TABLE #PASSENGERALLCURRENCY2 END TRY BEGIN CATCH END CATCH





SELECT P.*,

(CASE WHEN P.CURRENCYCODE <> P.AOCCURRENCY THEN P.FARE_REVENUE*(1/CCA.CONVERSIONRATE) ELSE P.FARE_REVENUE END) FARE_REV_AOCCURRENCY,

(CASE WHEN P.CURRENCYCODE <> P.AOCCURRENCY THEN P.FUEL_REV*(1/CCA.CONVERSIONRATE) ELSE P.FUEL_REV END) FUEL_REV_AOCCURRENCY

INTO #PASSENGERALLCURRENCY2

FROM

#PASSENGERALLCURRENCY1 P

LEFT JOIN

DW.CURRENCYCONVERSIONHISTORYDECOMPRESSED CCA

ON

CONVERT(DATE,CCA.CONVERSIONDATE,110) = CONVERT(DATE,P.BOOKINGDATE,110)

AND

CCA.FROMCURRENCYCODE = P.AOCCURRENCY

AND

CCA.TOCURRENCYCODE = P.CURRENCYCODE







BEGIN TRY DROP TABLE #PASSENGERALLCURRENCY END TRY BEGIN CATCH END CATCH





SELECT P.*,

(CASE WHEN P.CURRENCYCODE <> P.POSCOUNTRYCURRENCY THEN P.FARE_REVENUE*(1/CCP.CONVERSIONRATE) ELSE P.FARE_REVENUE END) FARE_REV_POSCURRENCY,

(CASE WHEN P.CURRENCYCODE <> P.POSCOUNTRYCURRENCY THEN P.FUEL_REV*(1/CCP.CONVERSIONRATE) ELSE P.FUEL_REV END) FUEL_REV_POSCURRENCY

INTO #PASSENGERALLCURRENCY

FROM

#PASSENGERALLCURRENCY2 P

LEFT JOIN

DW.CURRENCYCONVERSIONHISTORYDECOMPRESSED CCP

ON

CONVERT(DATE,CCP.CONVERSIONDATE,110) = CONVERT(DATE,P.BOOKINGDATE,110)

AND

CCP.FROMCURRENCYCODE = P.POSCOUNTRYCURRENCY

AND

CCP.TOCURRENCYCODE = P.CURRENCYCODE





BEGIN TRY DROP TABLE AAII_TEMP_SALESCHANNEL_DAILY END TRY BEGIN CATCH END CATCH



SELECT BOOKINGDATE, DATEPART(YYYY,BOOKINGDATE) BOOKINGYEAR, DATENAME(MM,BOOKINGDATE) BOOKINGMONTH,
('W'+CONVERT(VARCHAR(3),DATEPART(week, BookingDate))) as BookingWkYr,
('W'+CONVERT(VARCHAR(3),DATEPART(WEEK, DAY(BookingDate)))) as BookingWkMth,
CARRIERCODE,

(CASE WHEN ASCII(SUBSTRING(DEPARTURESTATION,1,1)) < ASCII(SUBSTRING(ARRIVALSTATION,1,1)) THEN DEPARTURESTATION + ARRIVALSTATION

	  WHEN ASCII(SUBSTRING(DEPARTURESTATION,1,1)) > ASCII(SUBSTRING(ARRIVALSTATION,1,1)) THEN ArrivalStation + DepartureStation

	  ELSE 

		CASE WHEN ASCII(SUBSTRING(DEPARTURESTATION,2,1)) < ASCII(SUBSTRING(ARRIVALSTATION,2,1)) THEN DEPARTURESTATION + ARRIVALSTATION

		WHEN ASCII(SUBSTRING(DEPARTURESTATION,2,1)) > ASCII(SUBSTRING(ARRIVALSTATION,2,1)) THEN ArrivalStation + DepartureStation

		ELSE

			CASE WHEN ASCII(SUBSTRING(DEPARTURESTATION,3,1)) < ASCII(SUBSTRING(ARRIVALSTATION,3,1)) THEN DEPARTURESTATION + ARRIVALSTATION

			WHEN ASCII(SUBSTRING(DEPARTURESTATION,3,1)) > ASCII(SUBSTRING(ARRIVALSTATION,3,1)) THEN ArrivalStation + DepartureStation

			ELSE DEPARTURESTATION+ARRIVALSTATION 

			END

		END

	 END) MARKETGROUP, DEPARTURESTATION+ARRIVALSTATION Sector,

 (case when DATEDIFF(DAY,BookingDate,DepartureDate) between 0 and 10 then '0-10'
     when DATEDIFF(DAY,BookingDate,DepartureDate)%10 = 0 then  CONVERT(varchar,(DATEDIFF(DAY,BookingDate,DepartureDate)/10)*10+1-10) + '-' + CONVERT(varchar,(DATEDIFF(DAY,BookingDate,DepartureDate)/10)*10)
     else CONVERT(varchar,(DATEDIFF(DAY,BookingDate,DepartureDate)/10)*10+1)+ '-' + CONVERT(varchar,(DATEDIFF(DAY,BookingDate,DepartureDate)/10)*10+10) end)
		 as PURCHASELEADDAYS,

RoleCode,SALESCHANNEL,CURRENCYCODE,ORGANIZATIONCODE,ORGANIZATIONNAME,ORGANIZATIONCOUNTRYCODE,CATEGORY,GROUPING SALESCHANNELGROUPING,

CASE WHEN INTERNATIONAL = 1 THEN 'INT' ELSE 'DOM' END DOM_INT,

DEPARTURECOUNTRYCODE+'-'+ARRIVALCOUNTRYCODE COUNTRYPAIR,

(CASE WHEN ASCII(SUBSTRING(DEPARTURECOUNTRYCODE,1,1)) < ASCII(SUBSTRING(ARRIVALCOUNTRYCODE,1,1)) THEN DEPARTURECOUNTRYCODE +'-'+ ARRIVALCOUNTRYCODE

	  WHEN ASCII(SUBSTRING(DEPARTURECOUNTRYCODE,1,1)) > ASCII(SUBSTRING(ARRIVALCOUNTRYCODE,1,1)) THEN ARRIVALCOUNTRYCODE +'-'+ DEPARTURECOUNTRYCODE

	  ELSE 

		CASE WHEN ASCII(SUBSTRING(DEPARTURECOUNTRYCODE,2,1)) < ASCII(SUBSTRING(ARRIVALCOUNTRYCODE,2,1)) THEN DEPARTURECOUNTRYCODE +'-'+ ARRIVALCOUNTRYCODE

		WHEN ASCII(SUBSTRING(DEPARTURECOUNTRYCODE,2,1)) > ASCII(SUBSTRING(ARRIVALCOUNTRYCODE,2,1)) THEN ARRIVALCOUNTRYCODE +'-'+ DEPARTURECOUNTRYCODE

		ELSE DEPARTURECOUNTRYCODE+'-'+ARRIVALCOUNTRYCODE 

		END

	 END) COUNTRYPAIRGROUP,

DEPARTURECOUNTRY DEPCOUNTRY,ARRIVALCOUNTRY ARRCOUNTRY,POSCOUNTRYNAME POSCOUNTRY, POSCOUNTRYCURRENCY POSCURRENCY,

COUNT(DISTINCT SEGMENTID) SEATSOLD,

SUM(FARE_REVENUE) FARE_REV_BOOKINGCURRENCY,

SUM(FUEL_REV) FUEL_REV_BOOKINGCURRENCY,

SUM(FARE_REV_MYR) FARE_REV_MYR,

SUM(FUEL_REV_MYR) FUEL_REV_MYR,

SUM(FARE_REV_AOCCURRENCY) FARE_REV_AOCCURRENCY,

SUM(FUEL_REV_AOCCURRENCY) FUEL_REV_AOCCURRENCY,

SUM(FARE_REV_POSCURRENCY) FARE_REV_POSCURRENCY,

SUM(FUEL_REV_POSCURRENCY) FUEL_REV_POSCURRENCY

 INTO AAII_TEMP_SALESCHANNEL_DAILY

 FROM #PASSENGERALLCURRENCY

 GROUP BY BOOKINGDATE,DATEPART(YYYY,BOOKINGDATE), DATENAME(MM,BOOKINGDATE),
 ('W'+CONVERT(VARCHAR(3),DATEPART(week, BookingDate))) ,
('W'+CONVERT(VARCHAR(3),DATEPART(WEEK, DAY(BookingDate)))) ,
 CARRIERCODE,

(CASE WHEN ASCII(SUBSTRING(DEPARTURESTATION,1,1)) < ASCII(SUBSTRING(ARRIVALSTATION,1,1)) THEN DEPARTURESTATION + ARRIVALSTATION

	  WHEN ASCII(SUBSTRING(DEPARTURESTATION,1,1)) > ASCII(SUBSTRING(ARRIVALSTATION,1,1)) THEN ArrivalStation + DepartureStation

	  ELSE 

		CASE WHEN ASCII(SUBSTRING(DEPARTURESTATION,2,1)) < ASCII(SUBSTRING(ARRIVALSTATION,2,1)) THEN DEPARTURESTATION + ARRIVALSTATION

		WHEN ASCII(SUBSTRING(DEPARTURESTATION,2,1)) > ASCII(SUBSTRING(ARRIVALSTATION,2,1)) THEN ArrivalStation + DepartureStation

		ELSE

			CASE WHEN ASCII(SUBSTRING(DEPARTURESTATION,3,1)) < ASCII(SUBSTRING(ARRIVALSTATION,3,1)) THEN DEPARTURESTATION + ARRIVALSTATION

			WHEN ASCII(SUBSTRING(DEPARTURESTATION,3,1)) > ASCII(SUBSTRING(ARRIVALSTATION,3,1)) THEN ArrivalStation + DepartureStation

			ELSE DEPARTURESTATION+ARRIVALSTATION 

			END

		END

	 END),DEPARTURESTATION+ARRIVALSTATION,

 (case when DATEDIFF(DAY,BookingDate,DepartureDate) between 0 and 10 then '0-10'
     when DATEDIFF(DAY,BookingDate,DepartureDate)%10 = 0 then  CONVERT(varchar,(DATEDIFF(DAY,BookingDate,DepartureDate)/10)*10+1-10) + '-' + CONVERT(varchar,(DATEDIFF(DAY,BookingDate,DepartureDate)/10)*10)
     else CONVERT(varchar,(DATEDIFF(DAY,BookingDate,DepartureDate)/10)*10+1)+ '-' + CONVERT(varchar,(DATEDIFF(DAY,BookingDate,DepartureDate)/10)*10+10) end),

RoleCode,SALESCHANNEL,CURRENCYCODE,ORGANIZATIONCODE,ORGANIZATIONNAME,ORGANIZATIONCOUNTRYCODE,CATEGORY,GROUPING,

CASE WHEN INTERNATIONAL = 1 THEN 'INT' ELSE 'DOM' END,

DEPARTURECOUNTRYCODE+'-'+ARRIVALCOUNTRYCODE,

(CASE WHEN ASCII(SUBSTRING(DEPARTURECOUNTRYCODE,1,1)) < ASCII(SUBSTRING(ARRIVALCOUNTRYCODE,1,1)) THEN DEPARTURECOUNTRYCODE +'-'+ ARRIVALCOUNTRYCODE

	  WHEN ASCII(SUBSTRING(DEPARTURECOUNTRYCODE,1,1)) > ASCII(SUBSTRING(ARRIVALCOUNTRYCODE,1,1)) THEN ARRIVALCOUNTRYCODE +'-'+ DEPARTURECOUNTRYCODE

	  ELSE 

		CASE WHEN ASCII(SUBSTRING(DEPARTURECOUNTRYCODE,2,1)) < ASCII(SUBSTRING(ARRIVALCOUNTRYCODE,2,1)) THEN DEPARTURECOUNTRYCODE +'-'+ ARRIVALCOUNTRYCODE

		WHEN ASCII(SUBSTRING(DEPARTURECOUNTRYCODE,2,1)) > ASCII(SUBSTRING(ARRIVALCOUNTRYCODE,2,1)) THEN ARRIVALCOUNTRYCODE +'-'+ DEPARTURECOUNTRYCODE

		ELSE DEPARTURECOUNTRYCODE+'-'+ARRIVALCOUNTRYCODE 

		END

	 END),

DEPARTURECOUNTRY,ARRIVALCOUNTRY,POSCOUNTRYNAME, POSCOUNTRYCURRENCY












END

















GO


