USE [REZAKWB01]
GO

/****** Object:  StoredProcedure [dbo].[AAII_DAILY_MGT_SALES_REPORT]    Script Date: 10/26/2015 10:35:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



--ALTER PROCEDURE [dbo].[AAII_DAILY_MGT_SALES_REPORT]
--AS

DECLARE @startDateUTC   datetime,
		@MYDateUTC		datetime,
		@timeZone		varchar(4),
		@startDate		datetime,
		@endtDate		datetime
	

--SET @timeZone = GETDATE()
--select @MYDateUTC  = ods.ConvertDate( 'MY', GETDATE(),0,0)
--SET @startDateUTC   = ods.ConvertDate( @timeZone,CAST(CONVERT(VARCHAR, DATEADD(day, 1, @MYDateUTC-1), 101) AS DateTime) , 1, 0 )

SET @startDate = CONVERT(DATE, DATEADD(mm, DATEDIFF(mm, 0, GETDATE()-1), 0), 110)
SET @endtDate =  CONVERT (DATE, GETDATE(),110)
	  
print @startDate 
print @endtDate




BEGIN TRY DROP TABLE #PASSENGERS END TRY BEGIN CATCH END CATCH

SELECT BK.BOOKINGID,BK.BOOKINGDATE,BK.STATUS,
BP.PASSENGERID,
PJS.SEGMENTID,PJS.JOURNEYNUMBER,PJS.SEGMENTNUMBER,PJS.FAREJOURNEYTYPE,
PJL.INVENTORYLEGID,
IL.CARRIERCODE,IL.DEPARTUREDATE,
AR.ROLECODE,
(CASE WHEN IL.CARRIERCODE IN ('AK','D7') THEN 'MYR' 
	  WHEN IL.CARRIERCODE IN ('FD','XJ') THEN 'THB'
	  WHEN IL.CARRIERCODE = 'QZ' THEN 'IDR'
	  WHEN IL.CARRIERCODE IN ('PQ','Z2') THEN 'PHP'
	  WHEN IL.CARRIERCODE  = 'XT' THEN 'USD'
	  WHEN IL.CARRIERCODE = 'I5' THEN 'INR'
	  ELSE 'MYR' END) LOCAL_CURRENCYCODE
INTO #PASSENGERS
FROM
(SELECT * FROM ODS.BOOKING
WHERE CONVERT (DATE, BOOKINGDATE,110) >= @startDate --CONVERT(DATE, DATEADD(mm, DATEDIFF(mm, 0, GETDATE()-1), 0), 110)
  AND CONVERT (DATE, BOOKINGDATE,110) < @endtDate --CONVERT (DATE, GETDATE(),110)
  ) BK
JOIN
ODS.BOOKINGPASSENGER BP
ON
BK.BOOKINGID = BP.BOOKINGID
JOIN
ODS.PASSENGERJOURNEYSEGMENT PJS
ON
BP.PASSENGERID = PJS.PASSENGERID
JOIN
ODS.PASSENGERJOURNEYLEG PJL
ON
PJS.PASSENGERID = PJL.PASSENGERID
AND
PJS.SEGMENTID = PJL.SEGMENTID
JOIN
ODS.INVENTORYLEG IL
ON
PJL.INVENTORYLEGID = IL.INVENTORYLEGID
AND IL.CARRIERCODE <> 'BF'
AND IL.STATUS <> 2
AND IL.LID > 0
LEFT JOIN
ods.AgentRole AR
ON BK.CreatedAgentID = AR.AgentID


/*

SELECT CARRIERCODE, COUNT (DISTINCT SEGMENTID) 
FROM #PASSENGERS
GROUP BY CARRIERCODE

--SELECT TOP 100 * FROM ods.AgentRole
--SELECT COUNT(DISTINCT SEGMENTID) FROM #PJCREVENUE
--SELECT TOP 100 * FROM ODS.Booking

SELECT DISTINCT CHARGETYPE, CHARGECODE FROM ODS.PASSENGERFEECHARGE
WHERE CHARGECODE IN ('APT','GST','KLIA2','ASC','APTF','AVL','PSC','PSF','SVT','UDF','APFC','IWJR')


SELECT * FROM SAT_ManagementReporting_SalesChannel


*/

BEGIN TRY DROP TABLE #PJCREVENUE END TRY BEGIN CATCH END CATCH

SELECT P.*,PJC.CurrencyCode,PJC.CREATEDDATE,
SUM(CASE WHEN PJC.CHARGETYPE IN (0,1,7,19)
THEN PJC.CHARGEAMOUNT*CTM.POSITIVENEGATIVEFLAG ELSE 0 END) FARE_REVENUE
INTO #PJCREVENUE 
 FROM
#PASSENGERS P
JOIN
ODS.PASSENGERJOURNEYCHARGE PJC
ON
P.PASSENGERID = PJC.PASSENGERID
AND
P.SEGMENTID = PJC.SEGMENTID
JOIN
DW.CHARGETYPEMATRIX CTM
ON
PJC.CHARGETYPE = CTM.CHARGETYPEID
GROUP BY
P.BOOKINGID,P.BOOKINGDATE,P.STATUS,P.PASSENGERID,P.SEGMENTID,P.JOURNEYNUMBER,P.SEGMENTNUMBER,P.FAREJOURNEYTYPE,P.INVENTORYLEGID,
P.CarrierCode,P.DepartureDate,P.LOCAL_CURRENCYCODE,P.ROLECODE,
PJC.CURRENCYCODE,PJC.CREATEDDATE

BEGIN TRY DROP TABLE #PJCR END TRY BEGIN CATCH END CATCH

SELECT  
--CONVERT (DATE, GETDATE(), 110) 
@endtDate CAPTUREDDATE, CONVERT (DATE, PJR.BOOKINGDATE,110) BOOKINGDATE,PJR.CARRIERCODE,PJR.STATUS,PJR.ROLECODE,
COUNT(DISTINCT PJR.SEGMENTID) SEAT_SOLD,
SUM(CASE WHEN PJR.CURRENCYCODE = PJR.LOCAL_CURRENCYCODE THEN PJR.FARE_REVENUE
		 ELSE PJR.FARE_REVENUE*(1/CC.CONVERSIONRATE) END) SALES_AMT
INTO #PJCR
FROM
#PJCREVENUE PJR
LEFT JOIN
DW.CURRENCYCONVERSIONHISTORYDECOMPRESSED CC
ON
CONVERT(DATE,PJR.CREATEDDATE,110) = CONVERT(DATE,CC.CONVERSIONDATE,110)
AND
PJR.CURRENCYCODE = CC.TOCURRENCYCODE
AND
PJR.LOCAL_CURRENCYCODE = CC.FROMCURRENCYCODE
GROUP BY 
CONVERT (DATE, PJR.BOOKINGDATE,110),PJR.CARRIERCODE,PJR.STATUS,PJR.ROLECODE

BEGIN TRY DROP TABLE AAII_TEMP_DAILY_SALES_MGT_REPORT END TRY BEGIN CATCH END CATCH

SELECT *
INTO AAII_TEMP_DAILY_SALES_MGT_REPORT
FROM #PJCR




GO


